export type ReadModelErrorCode =
  | 'INVALID_QUERY'
  | 'INVALID_TIME_RANGE'
  | 'RESULT_LIMIT_EXCEEDED'
  | 'INSTRUMENT_NOT_FOUND'
  | 'FILING_NOT_FOUND'
  | 'AMBIGUOUS_INSTRUMENT_VERSION'
  | 'AGENT_RUN_NOT_FOUND'
  | 'INVALID_TRANSITION'
  | 'INVALID_DAG'
  | 'INVALID_BODY'
  | 'RISK_DECISION_NOT_FOUND'
  | 'TRADING_DISABLED'
  | 'DECISION_NOT_APPROVED'
  | 'DECISION_NOT_ACTIONABLE'
  | 'INTENT_NOT_CANCELABLE'
  | 'ORDER_INTENT_NOT_FOUND'
  | 'RESEARCH_RUN_NOT_FOUND'
  | 'MODEL_VERSION_NOT_FOUND'
  | 'SIGNAL_NOT_FOUND'
  | 'BACKTEST_NOT_FOUND'
  | 'INVALID_MODEL_VERSION'
  | 'OPTION_POSITION_NOT_FOUND'
  | 'INVALID_OPTION_POSITION'
  | 'UPSTREAM_ERROR'
  | 'UPSTREAM_TIMEOUT'
  | 'MT5_DISCONNECTED'
  | 'BRIDGE_ERROR'
  | 'BRIDGE_AUTH_UNAVAILABLE'
  | 'INSUFFICIENT_DATA'
  | 'NOT_FOUND'
  | 'RATE_LIMITED'
  | 'INVALID_CODE'
  | 'PROPOSAL_EXPIRED'
  | 'INVALID_STATE'
  | 'NO_PRICE'
  | 'DEMO_ONLY'
  | 'INTERNAL_ERROR'
  // Item A (ML Híbrido — backtest econômico real, revisão 4):
  | 'FORBIDDEN'
  | 'COST_PROFILE_REQUIRED'
  | 'COST_PROFILE_NOT_FOUND'
  | 'INVALID_COST_PROFILE'
  | 'ARTIFACT_NOT_FOUND'
  | 'SYMBOL_NOT_IN_ARTIFACT'
  | 'INVALID_HASH'
  | 'ARTIFACT_UNREADABLE'
  | 'SNAPSHOT_NOT_FOUND'
  // Item C (treino ML assíncrono, persistido e cancelável):
  | 'TRAINING_RUN_NOT_FOUND'
  | 'TRAINING_RUN_ALREADY_ACTIVE'
  | 'TRAINING_RUN_NOT_CANCELABLE'
  | 'INVALID_TRAINING_RUN_TRANSITION'
  // Bloqueador 5 (revisão Guardião): payload do motor Python que falha a
  // validação estrita de runtime em `createHttpMlTrainJobPort`.
  | 'UPSTREAM_MALFORMED_RESPONSE'
  // Bloqueador 12 (revisão Guardião): principal não resolvido (sessão
  // ausente/inválida) tentando criar/listar/cancelar um MlTrainingRun.
  | 'UNAUTHENTICATED';

const STATUS_BY_CODE: Record<ReadModelErrorCode, number> = {
  INVALID_QUERY: 400,
  INVALID_TIME_RANGE: 400,
  RESULT_LIMIT_EXCEEDED: 400,
  INSTRUMENT_NOT_FOUND: 404,
  FILING_NOT_FOUND: 404,
  AMBIGUOUS_INSTRUMENT_VERSION: 409,
  AGENT_RUN_NOT_FOUND: 404,
  INVALID_TRANSITION: 409,
  INVALID_DAG: 400,
  INVALID_BODY: 400,
  RISK_DECISION_NOT_FOUND: 404,
  TRADING_DISABLED: 409,
  DECISION_NOT_APPROVED: 409,
  DECISION_NOT_ACTIONABLE: 409,
  INTENT_NOT_CANCELABLE: 409,
  ORDER_INTENT_NOT_FOUND: 404,
  RESEARCH_RUN_NOT_FOUND: 404,
  MODEL_VERSION_NOT_FOUND: 404,
  SIGNAL_NOT_FOUND: 404,
  BACKTEST_NOT_FOUND: 404,
  INVALID_MODEL_VERSION: 400,
  OPTION_POSITION_NOT_FOUND: 404,
  INVALID_OPTION_POSITION: 400,
  UPSTREAM_ERROR: 502,
  UPSTREAM_TIMEOUT: 504,
  MT5_DISCONNECTED: 503,
  BRIDGE_ERROR: 502,
  BRIDGE_AUTH_UNAVAILABLE: 503,
  INSUFFICIENT_DATA: 422,
  NOT_FOUND: 404,
  RATE_LIMITED: 429,
  INVALID_CODE: 403,
  PROPOSAL_EXPIRED: 410,
  INVALID_STATE: 409,
  NO_PRICE: 422,
  DEMO_ONLY: 403,
  INTERNAL_ERROR: 500,
  FORBIDDEN: 403,
  COST_PROFILE_REQUIRED: 400,
  COST_PROFILE_NOT_FOUND: 404,
  INVALID_COST_PROFILE: 400,
  ARTIFACT_NOT_FOUND: 404,
  SYMBOL_NOT_IN_ARTIFACT: 404,
  INVALID_HASH: 400,
  ARTIFACT_UNREADABLE: 422,
  SNAPSHOT_NOT_FOUND: 422,
  TRAINING_RUN_NOT_FOUND: 404,
  TRAINING_RUN_ALREADY_ACTIVE: 409,
  TRAINING_RUN_NOT_CANCELABLE: 409,
  INVALID_TRAINING_RUN_TRANSITION: 409,
  UPSTREAM_MALFORMED_RESPONSE: 502,
  UNAUTHENTICATED: 401,
};

/**
 * Stable, sanitized read-model error. `message` is always a fixed,
 * non-leaking string (never a raw Prisma/SQL/stack message). Route
 * handlers translate this directly into the wire error envelope.
 */
export class ReadModelError extends Error {
  readonly code: ReadModelErrorCode;
  readonly status: number;

  constructor(code: ReadModelErrorCode, message: string) {
    super(message);
    this.name = 'ReadModelError';
    this.code = code;
    this.status = STATUS_BY_CODE[code];
  }
}
